package entity


enum class GamePhase {
    DISCARD,
    KNOCKED,
    READYTODRAW,
    FINISHED,
    INITIALIZED,
    REVEAL,
    SHOW_STARTING_HANDS_1,
    SHOW_STARTING_HANDS_2,
    DRAW_FROM_DECK,DRAW_FROM_PILE,
    SHOW_CARDS,
    PLAY_QUEEN, PLAY_SEVEN_OR_EIGHT, PLAY_NINE_OR_TEN,PLAY_JACK,
    POWERCARD_DRAWN, PUNKTCARD_DRAWN,
    ENDTURN,
    confirmQueenShow,PLAYER_ADDITION,PLAYERS_ADDED
}